## **1. Numpy란?** ###

Numpy는 파이썬을 계산 혹은 분석에 이용할 때 쓰는 핵심 역할을 하는 라이브러리 중 하나이다.


**Numpy의 특징**
- np는 객체는 수학/ 통계 관련 함수 사용



- 다차원 배열 ndarray



- np는 블럭 연산 가능(배열 간의 계산등…)


- np는 다차원 배열 객체 생성



관례상 Scipy와 PyData를 사용하는 대부분의 사용자는 Numpy를 별칭(alias)인 np를 사용해 import 한다.


In [8]:
import numpy as np


import는 파이썬에서 라이브러리를 읽기 위해 사용하는 명령어이다.

Numpy는 외부라이브러리로 본래 파이썬을 다운받을 때 존재하지 않는 라이브러리이다. 그래서 이 모듈을 가져오기 위해서 import를 사용한다.


 ## ndarray 다차원 배열 객체
 
 ---
 

ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다. ndarray의 모든 원소는 같은 자료형이어야만 한다.


- shape : 모든 배열은 각 차원의 크기를 알려주는 튜플, 차원의 구조를 볼 때 사용 (행, 렬)로 표시됨.
 


- dtype : 배열에 저장된 자료를 알려주는 객체

 

 ## **1. 1 배열 생성 함수** ###





**np.array()**


- 순서가 있는 객체(주로 리스트)를  넘겨받아 데이터가 들어있는 새로운 NumPy 배열 생성



다차원 배열 생성시 배열의 길이가 동일해야 함.



다차원 배열은 일종의 매트릭스와도 비슷하다.



순서가 있는 배열은 벡터(;크기와 방향을 가진 양; 수와 순서쌍으로 구성)와도 비슷해보임




 - np.array.ndim : 차원 수 (행)


**np.zeros , np.ones**


 - 각각 0과 1이 들어있는 배열을 생성한다.

 - 다차원 배열을 생성하려면 (행,열)로된 튜플을 넘기면 된다.




In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

 
**np.empty**
 - 초기화가 없는 값으로 배열을 반환함



**np.arange(n)**


- 배열 버전의 range 함수, 자료형을 명시하지 않으면 float64임.









<img src="https://raw.githubusercontent.com/kkkjerry/python_camp/master/lecture/figures/ndarray.PNG">

## **2. Numpy 배열의 기초 (배열 슬라이싱 : 하위 배열에 접근하기)** ###

1차원 배열

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[:5]

array([0, 1, 2, 3, 4])

In [7]:
x[5:]

array([5, 6, 7, 8, 9])

In [9]:
x[4:7]

array([4, 5, 6])

In [10]:
x[::2]

array([0, 2, 4, 6, 8])

In [11]:
x[1::2]

array([1, 3, 5, 7, 9])

In [12]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
x[5::-2]

array([5, 3, 1])

### **실습 문제** ###

In [25]:
a=np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- 10부터 3 간격으로 요소를 거꾸로 나열해보자.

답변 ↓

## **3. Numpy 배열의 기초 (배열 인덱싱 : 단일 요소에 접근하기)** ###

- 배열 인덱싱은 개별 배열 요소값을 가져오고 설정할 수 있습니다.

- square bracket 안에 원하는 인덱스 값을 지정할 수 있습니다.

- 배열의 끝에서 부터 인덱싱할려면 음수 인덱스를 사용하면 됩니다. 

In [19]:
x1 = np.random.randint(10, size=((3,4)))
x1

array([[2, 2, 7, 2],
       [3, 1, 4, 1],
       [6, 7, 1, 9]])

In [22]:
x1[0,0]

12

In [23]:
x1[0,0] =12
x1

array([[12,  2,  7,  2],
       [ 3,  1,  4,  1],
       [ 6,  7,  1,  9]])

다차원 배열에서는 콤마로 구분된 인덱스 튜플을 이용해 배열 항목에 접근할 수 있습니다.

인덱스 표기법을 사용해 값을 수정할 수도 있습니다.

In [26]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[5, 2, 5, 5],
       [7, 2, 9, 6],
       [9, 9, 5, 8]])

In [27]:
x2[:2,:3]

array([[5, 2, 5],
       [7, 2, 9]])

### 실습 문제###

모든 행과 열은 하나씩 걸러서 나타내시오

In [ ]:
x2[    ???]

## **4. 배열의 재구조화** ##

* 초기 배열의 구조가 형상이 변경된 구조의 규모와 일치해야 한다.

In [32]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
grid.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
grid.reshape((3,2))

ValueError: cannot reshape array of size 9 into shape (3,2)

### **실습 문제** ###

* b=np.arange(4,10)
* b에 대해 2행 3열의 배열로 만드시오.

## **5. Numpy 배열 연산 : 유니버설 함수** ##
 
 

* 파이썬의 기본 구현에서 몇 가지 연산은 느리게 수행됩니다. 이는 부분적으로 파이썬이 동적인 인터프리터 언어이기 때문입니다. 


* 파이썬은 수많은 작은 연산이 반복되는 상황에서 확연히 느립니다.


 
 
 
 **cf) 인터프리터 언어란?**
 
 
- 소스코드를 바로 실행하는 컴퓨터 프로그램 또는 환경
- 인터프리터는 소스코드를 한줄 한줄 읽어들이면서 실행하는 프로그램
- **번역과 실행이 동시에 이루어집니다.**(별도의 실행파일이 존재하지 않습니다.)
- **자바스크립트, HTML, SQL, python,등**



**cf) 컴파일 언어란?**


- 소스코드에서 목적코드로 옮기는 것을 말합니다. 
- **번역과 실행이 따로 이루어집니다.**
- 긴 코드를 작성 해놓은 후 한번의 실행으로 해당 코드를 컴파일 과정을 거쳐 CPU에서 차례차례 실행이 되는 언어
- **C, C++, JAVA, C#등**



- NumPy는 정적 타입 체계를 가진 컴파일된 루틴에 편리한 인터페이스를 제공하는데 이를 벡터화 연산이라고 한다. 



- NumPy에서 벡터화 연산은 **NumPy 배열의 값에 반복된 연산을 빠르게 수행하는 것을 주목적으로 하는 ufuncs를 통해 구현된다.**



- 유니버설 함수는 매우 유연해서 두 배열 간의 연산도 가능하다.





 


In [39]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

 #### 배열 산술 연산- NumPy ufuncs는 파이썬의 기본 산술 연산자를 사용한다. 

In [41]:
x= np.arange(4)
print("x=",x)
print("x+5=",x+5)
print("x-5=",x-5)
print("x*2=",x*2)
print("x/2=",x/2)
print("x//2=",x//2) # 바닥 나눗셈( 나머지는 버림)

x= [0 1 2 3]
x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x//2= [0 0 1 1]


### 산술 연산은 사용상 편의를 위해 Numpy에 내장된 특정 함수로 감싼 것이다. 

In [43]:
np.add(x,5)

array([5, 6, 7, 8])

### 절댓값 함수에 대응하는 NumPy ufunc는 np.absolute로, np.abs라는 별칭으로도 사용가능하다.

복소수 데이터도 처리할 수 있으며, 이경우에는 절댓값은 크기를 반환한다.



In [48]:
x=np.array([-2,-1,0,1,2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [49]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [52]:
x=np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

### 삼각함수  - 데이터에서 가장 유용한 함수 중 일부는 삼각함수이다. 


In [55]:
theta = np.linspace( 0, np.pi, 3)

print("theta = ", theta)
print(" sin(theta)= ", np.sin(theta))
print(" cos(theta)= ", np.cos(theta))
print(" tan(theta)= ", np.tan(theta))


theta =  [0.         1.57079633 3.14159265]
 sin(theta)=  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
 cos(theta)=  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
 tan(theta)=  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### 지수와 로그

In [57]:
x=[1,2,3]
print("x = ",x)
print("e^x = ", np.exp(x) )
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [58]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


## 출력지정

* 대규모 연산인 경우, 연산 결과를 저장할 배열을 지정하는 것이 유용할 대가 있다. 임시배열을 생성하지 않고 지정한 배열을 이용해 원하는 메모리 위치에 직접 연산 결과를 쓸 수 있다. 


* 모든 ufuncs 에서 함수의 out 인수를 사용해 출력을 지정할 수 있다.

In [60]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [63]:
y = np.zeros(10)
np.multiply(2, x, out=y[::2])
print(y)

[0. 0. 2. 0. 4. 0. 6. 0. 8. 0.]


## 집계




* 배열을 특정 연산으로 축소하고자 한다면 reduce 메서드를 사용하면 됩니다. 


* reduce 메서드는 결과가 하나만 남을 때까지 해당 연산을 배열 요소에 반복해서 적용합니다.



In [64]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [65]:
np.multiply.reduce(x)

120

* 계산의 중간 결과를 모두 저장하고 싶다면 reduce 대신 accumulate 를 사용하면 됩니다. 

In [66]:
x = np.arange(1, 6)
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [67]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

## 6. 브로드 캐스팅

느린 파이썬 루프를 제거하기 위해 연산을 벡터화 하는 NumPy의 유니버설 함수 사용법을 했었다. 


벡터화 연산의 또 다른 방법은 NumPy의 브로드 캐스팅 기능을 사용하는 것이다.



### 브로드캐스팅은 단지 다른 크기의 배열에 유니버설 함수(덧셈, 뺄셈, 곱셈 등)를 적용하기 위한 규칙의 집합이다.


In [15]:
a = np.array([1,2,3])
b=np.array([1,2])

a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

<img src="https://raw.githubusercontent.com/kkkjerry/python_camp/master/lecture/figures/broadcasting.PNG">

브로드캐스팅은 어떤 조건만 만족한다면 모양이 다른 배열끼리의 연산도 가능하게 해주며 모양이 부족한 부분은 확장하여 연산을 수행할 수 있도록 한다.


확장 또는 전파한다는 의미로 Broadcasting을 설명하는 가장 간단한 예는 배열과 스칼라 값을 계산하는 것이다.

- 스칼라는 일반 상수를 생각하면 된다.




   
 

위의 그림에서는 첫 번째 그림에 해당하는 것으로 0, 1, 2라는 NumPy로 생성한 배열에 스칼라 5를 합한 결과가 5, 6, 7이라는 것을 알 수 있다. 일반적인 파이썬 리스트를 사용하면 for문을 이용해야 같은 결과를 얻을 수 있지만, NumPy에서는 브로드캐스팅의 개념 덕분에 5가 0이외에 1과 2의 원소 부분에도 전파(broadcast)되어 계산되어 간단하게 합 연산을 수행하는 것만으로 같은 결과를 얻을 수 있었다. 


두 번째 그림은 배열 간의 계산으로 배열의 차원이 확대된 케이스이다. 두 번째 그림은 3x3 배열에 1x3 배열을 합 연산한 경우이다. 각 행에 동일한 계산을 전파한 것을 볼 수 있다. 

 세번째 그림은 브로드캐스팅의 확장성 측면을 극명하게 보여주는 케이스이다. 3x1 배열과 1x3 배열의 합을 했는데 두 번째에서는 한쪽의 더 낮은 차원의 배열에서만 아래(0번 축) 방향으로 broadcast한 것에 반해 양 쪽 배열에서 broadcast한 것을 확인할 수 있다.

  **브로드캐스팅이 일어날 수 있는 조건은 다음과 같다.**
  
      • 규칙 1 : 두 배열의 차원 수가 다른 경우 치수가 더 작은 배열의 모양에 선행 (왼쪽)면이있는 모양이 채워집니다.



      • 규칙 2 : 두 배열의 모양이 임의의 차원에서 일치하지 않으면 해당 차원의 모양이 1 인 배열이 다른 모양과 일치하도록 늘어납니다.



      • 규칙 3 : 크기가 어느 정도라도 크기가 일치하지 않고 둘 다 1과 같으면 오류가 발생합니다.

In [16]:
a = np.array([1,2,3])
b=np.array([1,2])

a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
b.shape=(2,1)

a+b

array([[2, 3, 4],
       [3, 4, 5]])